### PR TITLE
Fix shadow hang when plugins start after the sim stop time

### LINKED ISSUE #1868: Shadow becomes stuck when the stop time is earlier than a process start time
This simulation causes shadow to become stuck, and it never exits.

```yaml
general:
  stop_time: 15s

network:
  graph:
    type: 1_gbit_switch

hosts:
  server:
    network_node_id: 0
    processes:
    - path: /bin/python3
      args: -m http.server 80
      start_time: 10s
  client:
    network_node_id: 0
    processes:
    - path: /bin/curl
      args: -s server
      start_time: 20s
```

These are the last few lines of the log file.

```
00:00:00.003637 [7618:shadow] n/a [INFO] [n/a] [controller.c:510] [controller_run] running simulation
00:00:00.003644 [7618:shadow] n/a [INFO] [n/a] [controller.c:514] [controller_run] log message buffering is enabled for efficiency
00:00:00.003694 [7626:shadow-worker] n/a [INFO] [n/a] [scheduler.c:69] [_scheduler_startHostsWorkerTaskFn] starting to boot 1 hosts
00:00:00.003785 [7626:shadow-worker] n/a [INFO] [n/a] [scheduler.c:71] [_scheduler_startHostsWorkerTaskFn] 1 hosts are booted
00:00:00.003805 [7627:shadow-worker] n/a [INFO] [n/a] [scheduler.c:69] [_scheduler_startHostsWorkerTaskFn] starting to boot 1 hosts
00:00:00.003852 [7627:shadow-worker] n/a [INFO] [n/a] [scheduler.c:71] [_scheduler_startHostsWorkerTaskFn] 1 hosts are booted
00:00:00.003990 [7618:shadow] n/a [INFO] [n/a] [manager.c:688] [_manager_heartbeat] process resource usage at simtime 10000000000 reported by getrusage(): ru_maxrss=0.172226 GiB, ru_utime=0.000000 minutes, ru_stime=0.000000 minutes, ru_nvcsw=82, ru_nivcsw=7
00:00:00.004124 [7627:shadow-worker] 00:00:10.000000000 [INFO] [server:11.0.0.2] [process.c:512] [_process_start] starting process 'server.python3.8.1000'
00:00:00.004162 [7627:shadow-worker] 00:00:10.000000000 [INFO] [server:11.0.0.2] [thread_preload.c:200] [threadpreload_run] forking new thread with environment 'SHADOW_SPAWNED=TRUE SHADOW_LOG_START_TIME=381648149397 SHADOW_LOG_LEVEL=3 SHADOW_INTERPOSE_METHOD=PRELOAD LD_PRELOAD=/shared/code/shadow/main/build/src/lib/injector_preload/libshadow_injector.so:/shared/code/shadow/main/build/src/lib/libc_preload/libshadow_libc.so:/shared/code/shadow/main/build/src/lib/openssl_preload/libshadow_openssl_rng.so SHADOW_SHM_PROCESS_BLK=24,134217728,8,/shadow_shmemfile_381648.151305180-7618 SHADOW_LOG_FILE=/tmp/sim/shadow.data/hosts/server/server.python3.8.1000.shimlog SHADOW_SHM_THREAD_BLK=40,134217728,1,/shadow_shmemfile_381648.151305180-7618 SHADOW_IPC_BLK=1032,134217728,648,/shadow_shmemfile_381648.151305180-7618 SHADOW_USE_SECCOMP= SHADOW_PID=7618 SHADOW_TSC_HZ=2592000000', arguments '/usr/bin/python3.8 -m http.server 80', and working directory '/tmp/sim/shadow.data/hosts/server'
00:00:00.004396 [7627:shadow-worker] 00:00:10.000000000 [INFO] [server:11.0.0.2] [process.c:547] [_process_start] process 'server.python3.8.1000' started
00:00:00.029728 [7627:shadow-worker] 00:00:10.000000000 [WARN] [server:11.0.0.2] [signal.c:290] [syscallhandler_sigaltstack] sigaltstack used, but is currently only partially emulated. Instability may result.
00:00:00.048742 [7627:shadow-worker] 00:00:10.000000000 [WARN] [server:11.0.0.2] [process.rs:285] [shadow_rs::host::process::export] A descriptor exists for fd=3, but it is not a legacy descriptor. Returning NULL.
00:00:00.048824 [7627:shadow-worker] 00:00:10.000000000 [WARN] [server:11.0.0.2] [process.rs:285] [shadow_rs::host::process::export] A descriptor exists for fd=3, but it is not a legacy descriptor. Returning NULL.
00:00:00.176983 [7627:shadow-worker] 00:00:10.000000000 [WARN] [server:11.0.0.2] [socket.c:1149] [syscallhandler_setsockopt] setsockopt called with unsupported level 41 with opt 26
00:00:00.179986 [7627:shadow-worker] 00:00:10.000000000 [WARN] [server:11.0.0.2] [process.rs:285] [shadow_rs::host::process::export] A descriptor exists for fd=4, but it is not a legacy descriptor. Returning NULL.
00:00:00.180069 [7627:shadow-worker] 00:00:10.000000000 [WARN] [server:11.0.0.2] [process.rs:285] [shadow_rs::host::process::export] A descriptor exists for fd=4, but it is not a legacy descriptor. Returning NULL.
00:00:00.180210 [7627:shadow-worker] 00:00:10.000000000 [INFO] [server:11.0.0.2] [dns.c:252] [_dns_writeNewHostsFile] Wrote new hosts file of size 52 bytes at path '/tmp/shadow-7618-hosts-9C7G6d'
00:00:00.181010 [7618:shadow] n/a [INFO] [n/a] [manager.c:688] [_manager_heartbeat] process resource usage at simtime 11500000000 reported by getrusage(): ru_maxrss=0.176399 GiB, ru_utime=0.000000 minutes, ru_stime=0.000000 minutes, ru_nvcsw=97, ru_nivcsw=2173
00:00:00.181577 [7618:shadow] n/a [INFO] [n/a] [manager.c:688] [_manager_heartbeat] process resource usage at simtime 13000000000 reported by getrusage(): ru_maxrss=0.176399 GiB, ru_utime=0.000000 minutes, ru_stime=0.000000 minutes, ru_nvcsw=106, ru_nivcsw=2176
00:00:00.181931 [7618:shadow] n/a [INFO] [n/a] [manager.c:688] [_manager_heartbeat] process resource usage at simtime 14500000000 reported by getrusage(): ru_maxrss=0.176399 GiB, ru_utime=0.000000 minutes, ru_stime=0.000000 minutes, ru_nvcsw=115, ru_nivcsw=2179
00:00:00.182043 [7626:shadow-worker] 00:00:15.000000000 [INFO] [n/a] [worker.c:476] [worker_finish] starting to shut down 1 hosts
00:00:00.182054 [7626:shadow-worker] 00:00:15.000000000 [INFO] [client:11.0.0.1] [process.c:641] [process_stop] terminating process 'client.curl.1000'
00:00:00.182082 [7626:shadow-worker] 00:00:15.000000000 [INFO] [client:11.0.0.1] [process.c:410] [_process_check] process 'client.curl.1000' has completed or is otherwise no longer running
```

### PR DESCRIPTION
**Pull request by stevenengler**
Closes #1868.

### CODE REVIEW

**Comment by sporksmith** [comment]
Do we know of a use case where this wouldn't be a mistake? Maybe it'd be better to catch this at config/setup time and exit with an error?

**Comment by stevenengler** [comment]
> Do we know of a use case where this wouldn't be a mistake? Maybe it'd be better to catch this at config/setup time and exit with an error?

It happens sometimes when I run a tornettools simulation with a `--stop-time 2min` for testing purposes. I think we could show a warning, but I don't think we need to exit.

File: src/main/host/process.c [hunk 1]
```diff
@@ -318,7 +318,7 @@ static void _process_handleTimerResult(Process* proc, gdouble elapsedTimeSec) {
 #endif
 
 static void _process_getAndLogReturnCode(Process* proc) {
-    if(!proc->didLogReturnCode) {
+    if(!proc->didLogReturnCode && process_hasStarted(proc)) {
```
Comment (sporksmith) [inline src/main/host/process.c:321]: Let's log a warning if the process hasn't started... maybe even an `error` so that it stand out more amongst the warnings about unimplemented syscalls. Unlike those, this happening in a "real" simulation is almost certainly a mistake.

**Review by sporksmith — APPROVED** [review]

File: src/main/host/process.c (hunk 1 above)
Comment (stevenengler) [reply src/main/host/process.c]: Added an error message to the beginning of `_process_getAndLogReturnCode()`.

**Review by sporksmith — APPROVED** [review]
