### PR TITLE
(Part 3) Command-line parsing and YAML config files in Rust

### LINKED ISSUE #773: More human-readable Shadow config
Support for a more human-readable format such as YAML would be nice as it would be easier to read/write/modify config files and would help us eventually move away from XML configuration files. This work could be split into multiple steps:

  - [x] (Merged in #803) - Create an external tool that converts between `shadow.config.xml` XML files and `shadow.config.yaml` YAML files (i.e., converts XML to YAML, and YAML to XML). 
  - [x] (Merged in #895) - Modify Shadow so that it will accept its XML configuration on stdin rather than requiring that we read it from the `shadow.config.xml` file. (It should be able to read from stdin or from a file.)
  - [x] (Merged in #972) - Convert existing tests from xml to yaml, and use the yaml2xml converter in the test cases.
  - [ ] Long term: add support to Shadow so it can natively read and understand YAML files.
  - [ ] Long term: new "options" section in the config file. Here we could specify any global options, and make it so that command line options could also instead be added to the yaml file (and Shadow internally would process the options using the same code for consistency whether the options are specified on the command line or in the config file).

As an example, the [small example in the shadow repo](https://github.com/shadow/shadow/blob/master/resource/examples/shadow.config.xml) currently looks like this in XML:

```xml
<shadow stoptime="3600">
  <topology><![CDATA[<?xml version="1.0" encoding="utf-8"?><graphml xmlns="http://graphml.graphdrawing.org/xmlns" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://graphml.graphdrawing.org/xmlns http://graphml.graphdrawing.org/xmlns/1.0/graphml.xsd">
  <key attr.name="packetloss" attr.type="double" for="edge" id="d6" />
  <key attr.name="latency" attr.type="double" for="edge" id="d5" />
  <key attr.name="packetloss" attr.type="double" for="node" id="d4" />
  <key attr.name="countrycode" attr.type="string" for="node" id="d3" />
  <key attr.name="bandwidthdown" attr.type="int" for="node" id="d2" />
  <key attr.name="bandwidthup" attr.type="int" for="node" id="d1" />
  <key attr.name="ip" attr.type="string" for="node" id="d0" />
  <graph edgedefault="undirected">
    <node id="isp">
      <data key="d0">0.0.0.0</data>
      <data key="d1">2251</data>
      <data key="d2">17038</data>
      <data key="d3">US</data>
      <data key="d4">0.0</data>
    </node>
    <edge source="isp" target="isp">
      <data key="d5">50.0</data>
      <data key="d6">0.01</data>
    </edge>
  </graph>
</graphml>
]]></topology>
  <plugin id="tgen" path="~/.shadow/bin/tgen"/>
  <host id="server">
    <process plugin="tgen" starttime="1" arguments="tgen.server.graphml.xml"/>
  </host>
  <host id="client">
    <process plugin="tgen" starttime="2" arguments="tgen.client.graphml.xml"/>
  </host>
</shadow>
```

And we could convert between XML and something like this in YAML:

```yaml
options:
    - stoptime: 3600

topology:
    - graphml: "<topology><![CDATA[<?xml version="1.0" encoding="utf-8"?><graphml xmlns="http://graphml.graphdrawing.org/xmlns" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://graphml.graphdrawing.org/xmlns http://graphml.graphdrawing.org/xmlns/1.0/graphml.xsd">
  <key attr.name="packetloss" attr.type="double" for="edge" id="d6" />
  <key attr.name="latency" attr.type="double" for="edge" id="d5" />
  <key attr.name="packetloss" attr.type="double" for="node" id="d4" />
  <key attr.name="countrycode" attr.type="string" for="node" id="d3" />
  <key attr.name="bandwidthdown" attr.type="int" for="node" id="d2" />
  <key attr.name="bandwidthup" attr.type="int" for="node" id="d1" />
  <key attr.name="ip" attr.type="string" for="node" id="d0" />
  <graph edgedefault="undirected">
    <node id="isp">
      <data key="d0">0.0.0.0</data>
      <data key="d1">2251</data>
      <data key="d2">17038</data>
      <data key="d3">US</data>
      <data key="d4">0.0</data>
    </node>
    <edge source="isp" target="isp">
      <data key="d5">50.0</data>
      <data key="d6">0.01</data>
    </edge>
  </graph>
</graphml>
]]></topology>"

plugins:
    - id: tgen
      path: ~/.shadow/bin/tgen

hosts:
    - id: server
      bandwidthdown: 102400
      bandwidthup: 102400                                                                                                                    
      processes:
          - plugin: tgen
            starttime: 1
            arguments: tgen.server.graphml.xml                                                                                          
    - id: client
      bandwidthdown: 102400
      bandwidthup: 102400                                                                                                                    
      processes:
          - plugin: tgen
            starttime: 2
            arguments: tgen.client.graphml.xml      
```

**NOTE:** We should continue to support graphml for the network topology graphs because we use igraph to read and to store the graph internally and to do graph operations on it (path lookups etc.). For anything but trivial examples, [the network graph I use](https://tmodel-ccs2018.github.io/data/shadow/network/atlas-lossless.201801.shadow113.graphml.xml.xz) is quite large, and I usually don't want to reproduce that in the config file. Also, I almost always use the same graph, so having a path to it works well. For trivial graphs, like the ones usually included in the examples, we will have to either read from the YAML format and then programmatically build up an igraph graph, or specify the graph in [a format that igraph understands](https://igraph.org/c/doc/igraph-Foreign.html). We chose graphml since it is common, and I don't see a reason for moving away from it now.

### PR DESCRIPTION
**Pull request by stevenengler**
Replaces Shadow's existing command-line and configuration file parsing code with Rust versions using [Serde](https://serde.rs/) and [Clap](https://docs.rs/clap/2.33.3/clap/) (version 3.0.0-beta.2). Shadow's XML configuration file format has been replaced by YAML in the process.

This PR will be easier to review as individual commits.

Closes #773.

Changed CLI options:

```
Old options                                                 New options
-----------                                                 -----------

-?, --help                                                  -h, --help
--help-all
--help-sys
--help-experimental
--interface-buffer=N                    [1024000]           --interface-buffer                  ["1024000 B"]
--interface-qdisc=QDISC                 ['fifo']            --interface-qdisc                   ["fifo"]
--socket-recv-buffer=N                  [174760]            --socket-recv-buffer                ["174760 B"]
                                                            --socket-recv-autotune              [true]
--socket-send-buffer=N                  [131072]            --socket-send-buffer                ["131072 B"]
                                                            --socket-send-autotune              [true]
--max-concurrency=N                     [-1]                --max-concurrency
--set-sched-fifo                                            --use-sched-fifo                    [false]
--disable-object-counters                                   --use-object-counters               [true]
--disable-shim-syscall-handler                              --use-shim-syscall-handler          [true]
--disable-o-n-waitpid-workarounds                           --use-o-n-waitpid-workarounds       [true]
--send-explicit-block-message=[0|1]     [1]                 --use-explicit-block-message        [true]
--enable-syscall-counters                                   --use-syscall-counters              [false]
--disable-memory-manager                                    --use-memory-manager                [true]
--preload-spin-max=N                    [8096]              --preload-spin-max                  [8096]
                                                            --bootstrap-end-time                ["0 sec"]
                                                            --heartbeat-interval                ["1 sec"]
                                                            --stop-time
                                                            --bandwidth-down
                                                            --bandwidth-up
                                                            --city-code-hint
                                                            --country-code-hint
                                                            --ip-hint
                                                            --pcap-directory
                                                            --type-hint
-c, --exit-after-shm-cleanup                                --shm-cleanup
-d, --data-directory=PATH               ['shadow.data']     -d, --data-directory                ["shadow.data"]
-e, --data-template=PATH                [None]              -e, --template-directory
-g, --gdb                                                   -g, --gdb
-h, --heartbeat-frequency=N             [1]                 --heartbeat-interval                ["1 sec"]
-i, --heartbeat-log-info=LIST           ['node']            --host-heartbeat-log-info           [["node"]]
-j, --heartbeat-log-level=LEVEL         ['message']         --host-heartbeat-log-level          ["message"]
                                                            --host-log-level
-l, --log-level=LEVEL                   ['message']         -l, --log-level                     ["message"]
-r, --runahead=TIME                     [0]                 --runahead
-s, --seed=N                            [1]                 --seed                              [1]
-t, --scheduler-policy=SPOL             ['steal']           --scheduler-policy                  ["steal"]
-n, --interpose-method=METHOD           ['ptrace']          --interpose-method                  ["ptrace"]
-z, --pin-cpus                                              --use-cpu-pinning                   [false]
-w, --workers=N                         [0]                 -w, --workers                       [0]
-v, --version                                               -V, --version
                                                            --show-build-info
                                                            --show-config
```

Changed configuration options:

```
bootstraptime         bootstrap_end_time
starttime             start_time
stoptime              stop_time
arguments             args
iphint                ip_hint
citycodehint          city_code_hint
countrycodehint       country_code_hint
typehint              type_hint
loglevel              log_level
heartbeatloglevel     heartbeat_log_level
heartbeatloginfo      heartbeat_log_info
pcapdir               pcap_directory
bandwidthdown         bandwidth_down (unit changed from KiB/s to bits)
bandwidthup           bandwidth_up (unit changed from KiB/s to bits)
heartbeatfrequency    heartbeat_interval
socketrecvbuffer      socket_recv_buffer
socketsendbuffer      socket_send_buffer
interfacebuffer       interface_buffer
```

Changed topology options:

```
bandwidthup      bandwidth_up (type changed to "string", and unit changed to bits)
bandwidthdown    bandwidth_down (type changed to "string", and unit changed to bits)
packetloss       packet_loss
countrycode      country_code
citycode         city_code
```

Miscellaneous changes:

- added a `quantity` field for processes
- renamed the configuration file top-level `options` field to `general`, and added new experimental options under the top-level `experimental` field, and new host default options under the top-level `host_defaults` field.
- hosts in the configuration file are now specified using a map/dictionary, and not a list of hosts
- moved some existing options into the `experimental` group (#1220)
- topology in the configuration file is no longer a list
- most of the host options have moved into an `options` field
- added a `plain` topology option (in addition to the existing `graphml` and `path` options), which uses a simple built-in topology (#1221)
- process arguments in the configuration file can now be passed as a list of arguments
- the existing XML/YAML conversion script has been modified to convert to the new YAML format, and no longer converts from YAML to XML
- added a new script for converting the topology graphml file to the new format
- removed the configuration file plugin list, and now each process specifies the path to the executable to run (#1147)
- disabled the XML/YAML conversion tests
- the `logpcap` and `pcapdir` options have been combined into a single option `pcap_directory`
- removed some of the short option flags (`-h`, `-i`, `-j`, etc)
- removes legacy configuration options suck as `kill` and `time` (#1146)
- values can be provided with a unit value (for example "1 Mbit", "1 megabit", etc) and if a unit isn't given, will default to the base unit (#1161)
- environment field is now per-process rather than global
- arguments are no longer split by spaces

To do after this PR:
- update tornettools to support new formats
- add PR for new/modified conversion scripts
- update and re-enable the XML/YAML conversion tests
- update documentation ([3.1-Shadow-Config.md](https://github.com/shadow/shadow/blob/dev/docs/3.1-Shadow-Config.md), [3.2-Network-Config.md](https://github.com/shadow/shadow/blob/dev/docs/3.2-Network-Config.md))

### CODE REVIEW

File: src/main/routing/topology.c [hunk 1]
```diff
@@ -241,6 +243,30 @@ static gboolean _topology_isValidEdgeAttributeKey(const gchar* attrName, EdgeAtt
...
+    if (igraph_cattribute_has_attr(&top->graph, IGRAPH_ATTRIBUTE_VERTEX, name)) {
+        const gchar* value = igraph_cattribute_VAS(&top->graph, name, vertexIndex);
+        if (value != NULL && value[0] != '\0') {
+            if (valueOut != NULL) {
+                int64_t bandwidth = parse_bandwidth(value);
+                if (bandwidth >= 0) {
+                    // parse_bandwidth() returns bits-per-second, but shadow works with KiB/s
+                    bandwidth /= 8 * 1024;
+                    *valueOut = bandwidth;
+                    return TRUE;
```
Comment (robgjansen) [inline src/main/routing/topology.c:261]: I think we are planning to remove KiB/s and just pass around bits or bytes. Do we need a TODO here for when we address that?

File: src/test/CMakeLists.txt [hunk 2]
```diff
@@ -70,13 +70,12 @@ macro(add_shadow_tests)
       
       set(SHADOW_TEST_COMMAND sh -c "\
          rm -rf ${SHADOW_TEST_NAME}.data \
-         && ${yaml2xml} ${SHADOW_TEST_SHADOW_CONFIG} --output - \
-         | ${CMAKE_BINARY_DIR}/src/main/shadow \
+         && ${CMAKE_BINARY_DIR}/src/main/shadow \
```
Comment (robgjansen) [inline src/test/CMakeLists.txt:73]: Woo! :)

File: src/test/clone/clone.yaml [hunk 3]
```diff
@@ -1,32 +1,8 @@
...
+  stop_time: 10
+topology: plain
 hosts:
-- id: host
-  quantity: 1
-  processes:
-  - plugin: test_clone
-    starttime: 1
-    arguments: ''
+  host:
```
Comment (robgjansen) [inline src/test/clone/clone.yaml:5]: Super-nit: can we change the name of the host to something that is more apparently a hostname instead of `host`?

File: src/test/determinism/determinism1.test.shadow.config.yaml [hunk 4]
```diff
@@ -1,32 +1,28 @@
...
+      <key attr.name="bandwidth_up" attr.type="string" for="node" id="d2" />
+      <key attr.name="bandwidth_down" attr.type="string" for="node" id="d1" />
+      <key attr.name="country_code" attr.type="string" for="node" id="d0" />
       <graph edgedefault="undirected">
         <node id="poi-1">
           <data key="d0">US</data>
-          <data key="d1">10240</data>
-          <data key="d2">10240</data>
+          <data key="d1">81920 Kibit</data>
+          <data key="d2">81920 Kibit</data>
```
Comment (robgjansen) [inline src/test/determinism/determinism1.test.shadow.config.yaml:15]: I think you want this to be `Kibibit` instead of `Kibit`?
https://en.wikipedia.org/wiki/Kibibit

This same problem applies to all of the yaml files in the PR that contain topology graphml code. I'm only noting it here, but you should change it everywhere.

File: src/test/tor/minimal/tor-minimal.yaml [hunk 5]
```diff
@@ -30,114 +28,112 @@ topology:
...
-    arguments: --Address torhiddenclient --Nickname torhiddenclient --DataDirectory .
-      --GeoIPFile ~/.shadow/share/geoip --defaults-torrc ../../../conf/tor.common.torrc
-      -f ../../../conf/tor.client.torrc --BandwidthRate 1024000 --BandwidthBurst 1024000
-  - plugin: tgen
-    starttime: 1500
-    arguments: ../../../conf/tgen.torhiddenclient.graphml.xml
+  fileserver:
+    options:
+      bandwidth_down: 819200 Kibit
+      bandwidth_up: 819200 Kibit
```
Comment (robgjansen) [inline src/test/tor/minimal/tor-minimal.yaml:35]: Some more `Kibit` -> `Kibibit` conversions here.

File: src/test/tor/minimal/tor-minimal.yaml [hunk 6]
```diff
@@ -30,114 +28,112 @@ topology:
...
+    processes:
+    - path: ~/.shadow/bin/tgen
+      args: ../../../conf/tgen.server.graphml.xml
+      start_time: 1
+  hiddenserver:
+    options:
+      bandwidth_down: 819200 Kibit
+      bandwidth_up: 819200 Kibit
```
Comment (robgjansen) [inline src/test/tor/minimal/tor-minimal.yaml:43]: Should we just set this bandwidth as the default for everyone in the `host_defaults` part of the config? Then we wouldn't need to duplicate it for each host.

Or even better, the topology only contains a single node, and that node already has the correct bandwidth, so I think all the hosts will already get assigned that bandwidth even if we don't specify it as a host option or host_default option.

**Review by robgjansen — CHANGES_REQUESTED** [review]
This looks great! It simplifies a lot of things and will make it much simpler to configure experiments. I'm looking forward to using this new format in my experiments :)

I don't have any complex changes, but I'd like to look at any changes you make anyway :)

File: src/test/determinism/determinism1.test.shadow.config.yaml (hunk 4 above)
Comment (stevenengler) [reply src/test/determinism/determinism1.test.shadow.config.yaml:15]: Do you want to change this to `Kibibit` just as a preference, or is there an issue with `Kibit`? Right now the configuration parsing will accept units in both `kibibit` (the full unit name) and `Kibit` (the unit symbol).

File: src/test/tor/minimal/tor-minimal.yaml (hunk 6 above)
Comment (stevenengler) [reply src/test/tor/minimal/tor-minimal.yaml:43]: Some hosts have bandwidths of 819200 kibibit (102400 KiB/s), some have 81920 kibibit (10240 KiB/s), clients have no defined bandwidths, and the topology node has a bandwidth of 81920 kibibit. Is there a reason why the original configuration had these hosts with different bandwidths? And why some hosts had bandwiths 10x greater than the topology node? Since this is just a test, it should be fine giving them all the same bandwidth, right?

File: src/test/determinism/determinism1.test.shadow.config.yaml (hunk 4 above)
Comment (robgjansen) [reply src/test/determinism/determinism1.test.shadow.config.yaml:15]: Oh shit, this is my bad, I had never seen `Kibit` before and I missed this part on the wiki page:

> The unit symbol of the kibibit is Kibit

So never mind, I think how you have it is fine.

File: src/test/tor/minimal/tor-minimal.yaml (hunk 5 above)
Comment (robgjansen) [reply src/test/tor/minimal/tor-minimal.yaml:35]: Never mind, `Kibit` is fine.

File: src/test/tor/minimal/tor-minimal.yaml (hunk 6 above)
Comment (robgjansen) [reply src/test/tor/minimal/tor-minimal.yaml:43]: Right, I don't think the bandwidths matter much in this small test. I think they can all be the same. Not sure why they were different before - probably because I decided that many many years ago and never changed it.

File: src/test/determinism/determinism1.test.shadow.config.yaml (hunk 4 above)
Comment (stevenengler) [reply src/test/determinism/determinism1.test.shadow.config.yaml:15]: > So never mind, I think how you have it is fine.

Okay, and if you would still prefer "kibibit" just let me know, it's an easy change.

File: src/main/core/main.c [hunk 7]
```diff
@@ -150,56 +147,83 @@ gint main_runShadow(gint argc, gchar* argv[]) {
...
     }
 
+    char* configName = clioptions_getConfig(options);
+
+    /* read config from file or stdin */
+    ConfigFileOptions* configFile = NULL;
+    if (strcmp(configName, "-") != 0) {
+        configFile = configfile_parse(configName);
+    } else {
+        configFile = configfile_parse("/dev/stdin");
```
[the remark this answers is not in the document]
Comment (stevenengler) [reply src/main/core/main.c:189]: Added a comment.

File: src/main/core/main.c [hunk 8]
```diff
@@ -150,56 +147,83 @@ gint main_runShadow(gint argc, gchar* argv[]) {
...
+        clioptions_free(options);
+        return EXIT_FAILURE;
+    }
+
+    /* generate the final shadow configuration from the config file and cli options */
+    ConfigOptions* config = config_new(configFile, options);
+    configfile_free(configFile);
+
+    if (clioptions_getShowConfig(options)) {
+        config_showConfig(config);
```
[the remark this answers is not in the document]
Comment (stevenengler) [reply src/main/core/main.c:205]: Added.

File: src/main/core/support/config_handlers.c [hunk 9]
```diff
@@ -0,0 +1,24 @@
...
+
+void runConfigHandlers(const ConfigOptions* config) {
+    if (experimentalOptions == NULL) {
+        return;
+    }
+    for (int i = 0; i < experimentalOptions->len; i++) {
+        ConfigHandlerFn fn = g_array_index(experimentalOptions, ConfigHandlerFn, i);
+        fn(config);
+    }
+    g_array_free(experimentalOptions, true);
```
[the remark this answers is not in the document]
Comment (stevenengler) [reply src/main/core/support/config_handlers.c:23]: Good idea, added.

File: src/main/core/support/config_handlers.h [hunk 10]
```diff
@@ -0,0 +1,19 @@
...
+
+typedef void (*ConfigHandlerFn)(const ConfigOptions*);
+
+void addConfigHandler(ConfigHandlerFn fun_ptr);
+void runConfigHandlers(const ConfigOptions* config);
+
+// Used to generate unique symbol names. See
+// https://stackoverflow.com/questions/1597007/creating-c-macro-with-and-line-token-concatenation-with-positioning-macr
+#define OPTIONS_TOKENPASTE(x, y) x##y
+#define OPTIONS_TOKENPASTE2(x, y) OPTIONS_TOKENPASTE(x, y)
```
[the remark this answers is not in the document]
Comment (stevenengler) [reply src/main/core/support/config_handlers.h:11]: I don't think we can `undef` them since they're used by the `ADD_CONFIG_HANDLER` macro. (The build fails when I undef them.)

File: src/main/routing/topology.c (hunk 1 above)
Comment (stevenengler) [reply src/main/routing/topology.c]: Added a TODO (and in `_controller_registerHostCallback()` also).

File: src/test/clone/clone.yaml (hunk 3 above)
Comment (stevenengler) [reply src/test/clone/clone.yaml]: Changed to `testnode` like the other tests.

File: src/test/tor/minimal/tor-minimal.yaml (hunk 6 above)
Comment (stevenengler) [reply src/test/tor/minimal/tor-minimal.yaml]: Changed the topology bandwidth to `1 Gbit` (rounded up from the ~800 Mbit that most hosts were using) and unset all of the other bandwidths.

**Review by robgjansen — APPROVED** [review]
Looks great! Thanks for the changes :)
