### PR TITLE
Fix shortest path logic for undirected graphs

### LINKED ISSUE #1345: "undirected" attribute not being honored
**Describe the issue**
In creating a topology, I set `<graph edgedefault="undirected">`, however, unless I specify edges in both directions, shadow fails with
```
**ERROR ENCOUNTERED**
	At process: 1272 (parent 23041)
	At file: /home/vagrant/shadow/src/main/routing/topology.c
	At line: 1722
	At function: _topology_computeSourcePaths
	Message: vertexIndexPointer != NULL
**BEGIN BACKTRACE**
Obtained 15 stack frames:
	shadow(+0x670c3) [0x55d8b0eb60c3]
	shadow(utility_handleError+0x3c) [0x55d8b0eb61ee]
	shadow(+0x61f03) [0x55d8b0eb0f03]
	shadow(+0x63120) [0x55d8b0eb2120]
	shadow(topology_getLatency+0x62) [0x55d8b0eb2347]
	shadow(+0x6346b) [0x55d8b0eb246b]
	shadow(host_connectToPeer+0x1a6) [0x55d8b0ea2ccd]
	shadow(+0x3b672) [0x55d8b0e8a672]
	shadow(process_emu_connect+0x186) [0x55d8b0e8c887]
	/home/vagrant/.shadow/lib/libshadow-interpose.so(connect+0x45) [0x7f4bc61cada2]
	shadow(pth_connect_ev+0x165) [0x55d8b0ec22c2]
	shadow(pth_connect+0x28) [0x55d8b0ec215b]
	shadow(process_emu_connect+0x11f) [0x55d8b0e8c820]
	/home/vagrant/.shadow/lib/libshadow-interpose.so(connect+0x45) [0x7f4bc61cada2]
	/home/vagrant/.shadow/bin/tgen(tgentransport_newActive+0x183) [0x7f4bbb3c8dd3]
**END BACKTRACE**
**ABORTING**
Segmentation fault (core dumped)
```

In other words, even though I specified that the graph should be undirected, it requires both directions to be defined.

**To Reproduce**
Topology file used:
```xml
<?xml version="1.0" encoding="utf-8"?><graphml
xmlns="http://graphml.graphdrawing.org/xmlns"
xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xsi:schemaLocation="http://graphml.graphdrawing.org/xmlns
http://graphml.graphdrawing.org/xmlns/1.0/graphml.xsd">
  <key attr.name="packetloss" attr.type="double" for="edge" id="d6" />
  <key attr.name="latency" attr.type="double" for="edge" id="d5" />
  <key attr.name="packetloss" attr.type="double" for="node" id="d4" />
  <key attr.name="countrycode" attr.type="string" for="node" id="d3" />
  <key attr.name="bandwidthdown" attr.type="int" for="node" id="d2" />
  <key attr.name="bandwidthup" attr.type="int" for="node" id="d1" />
  <key attr.name="ip" attr.type="string" for="node" id="d0" />
  <graph edgedefault="undirected">
    <node id="n1">
      <data key="d0">0.0.0.0</data>
      <data key="d1">5000</data>
      <data key="d2">50000</data>
      <data key="d3">US</data>
      <data key="d4">0.0</data>
    </node>
    <node id="n2">
      <data key="d0">0.0.0.0</data>
      <data key="d1">5000</data>
      <data key="d2">50000</data>
      <data key="d3">US</data>
      <data key="d4">0.0</data>
    </node>
    <edge source="n1" target="n2">
      <data key="d5">50.0</data>
      <data key="d6">0.01</data>
    </edge>
    <!-- <edge source="n2" target="n1"> -->
    <!--   <data key="d5">50.0</data> -->
    <!--   <data key="d6">0.01</data> -->
    <!-- </edge> -->
  </graph>
</graphml>
```

**Operating System (please complete the following information):**
 - OS and version: `Ubuntu 18.04.5 LTS`
 - Kernel version: `Linux ubuntu1804.localdomain 4.15.0-124-generic #127-Ubuntu SMP Fri Nov 6 10:54:43 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux`

**Shadow (please complete the following information):**
 - Version: `Shadow v1.13.2-704-g27f0e792 2021-05-03--16:38:19 running GLib v2.56.4 and IGraph v0.7.1
Shadow was built from branch main on 2021-05-10--21:28:11 in Debug mode with compile options: -ggdb;-fno-omit-frame-pointer;-O0 and link options: -Wl,--no-as-needed,-rpath=/home/vagrant/.shadow/lib,-dynamic-linker=/home/vagrant/.shadow/lib/ldso -z lazy`
 - Which plug-ins you are using: Shadow-Tor

### PR DESCRIPTION
**Pull request by robgjansen**
Fixes #1345.

### CODE REVIEW

File: src/main/routing/topology.c [hunk 1]
```diff
@@ -1823,8 +1823,20 @@ static gboolean _topology_computeSourcePaths(Topology* top, igraph_integer_t src
...
+    //   is stored in the last entry.
+    // So now we go through and cache all of the incremental shortest paths that we
+    // happened to compute while building the full path between source and destination.
+
+    // Skip over the source if it is included in the resultPaths list.
+    gint startingPosition = numTargets == 1 ? 0 : 1;
+
     /* go through the result paths for all targets */
-    for(gint position = 0; position < numTargets; position++) {
+    for (gint position = startingPosition; position < numTargets; position++) {
```
Comment (stevenengler) [inline src/main/routing/topology.c:1839]: I don't really understand the comments here. My understanding is that `resultPaths` contains a list of lists of vertices (a path for each target vertex), but the comments only seem to be discussing a specific path.

> Otherwise, the first entry stores the source vertex, and the destination vertex is stored in the last entry.

Won't the `resultPaths` element where the target is the destination vertex be stored in entry `dstVertexIndexPosition`? And why is it assumed that the first `resultPaths` element is a path to the source vertex? Doesn't this depend on the output of `_topology_getUniqueVertexTargets` where the targets may be in any order?

Comment (robgjansen) [reply src/main/routing/topology.c:1839]: Yeah you're right! This change is incorrect and I'll need to fix it.

**Review by stevenengler — APPROVED** [review]
