### PR TITLE
Fix sending packets from sockets bound to 0.0.0.0

### LINKED ISSUE #3088: UDP sockets bound to 0.0.0.0 cannot send packets
When a UDP socket informs the host that it has packets to send, it calls the host's `notify_socket_has_packets` method. This method takes an IP address, but it's not clear what this IP address is supposed to be. In `notify_socket_has_packets`, the IP address is passed to the network namespace's `interface_borrow` method, which returns a network interface for that IP address. The `notify_socket_has_packets` then notifies that returned network interface that there are packets to send. This means that the provided IP address must be either 127.0.0.1 or the host's public IP address. If the IP address is anything else, then the `notify_socket_has_packets` returns without doing anything. If a UDP socket is bound to 0.0.0.0 and gives this wildcard IP address to `notify_socket_has_packets`, nothing happens since that isn't one of these two IP addresses. It's unclear what IP address the UDP socket is supposed to give to `notify_socket_has_packets`. Should it call `notify_socket_has_packets` twice, once with each IP address? This seems like it could be bad since both network interfaces will be trying to send packets at the same time. And if the loopback interface tried to send a non-localhost packet, that would be a problem. So it should probably call `notify_socket_has_packets` once with the public IP address. But maybe `notify_socket_has_packets` should handle 0.0.0.0 instead. All of our integration tests send UDP messages only over localhost, so this bug wasn't caught by them.

### PR DESCRIPTION
**Pull request by stevenengler**
I don't think this is a proper fix since it means that localhost packets from sockets bound to 0.0.0.0 will be sent over the internet interface rather than the loopback interface. But I don't think there's anything else we can do here. The C TCP code does [something](https://github.com/shadow/shadow/issues/3088#issuecomment-1668389960) slightly different, but I don't think it's better than using just the internet interface.

Closes #3088.

### CODE REVIEW

File: src/main/host/network/namespace.rs [hunk 1]
```diff
@@ -147,7 +147,7 @@ impl NetworkNamespace {
     ) -> Option<impl Deref<Target = NetworkInterface> + '_> {
         if addr.is_loopback() {
             Some(self.localhost.borrow())
-        } else if addr == self.default_ip {
+        } else if addr == self.default_ip || addr.is_unspecified() {
```
Comment (sporksmith) [inline src/main/host/network/namespace.rs:150]: Maybe worth a comment here that this is a (temporary?) workaround with not-quite-right behavior?

File: src/main/host/network/namespace.rs [hunk 2]
```diff
@@ -162,7 +162,7 @@ impl NetworkNamespace {
     ) -> Option<impl Deref<Target = NetworkInterface> + DerefMut + '_> {
         if addr.is_loopback() {
             Some(self.localhost.borrow_mut())
-        } else if addr == self.default_ip {
+        } else if addr == self.default_ip || addr.is_unspecified() {
```
Comment (sporksmith) [inline src/main/host/network/namespace.rs:165]: same here

**Review by sporksmith — APPROVED** [review]

File: src/main/host/network/namespace.rs (hunk 1 above)
Comment (stevenengler) [reply src/main/host/network/namespace.rs:157]: Added some comments.

File: src/main/host/network/namespace.rs (hunk 2 above)
Comment (stevenengler) [reply src/main/host/network/namespace.rs:179]: Added the same comments as above.
