### PR TITLE
Re-schedule syscall condition after spurious wakeup

### LINKED ISSUE #1623: tgen getting stuck in epoll_wait after ~8m-15m simulated time in tor simulations
First noticed the problem running tor congestion control simulations in https://gitlab.torproject.org/jnewsome/sponsor-61-sims. Traced failed transfers to the tgen servers appearing to get deadlocked after somewhere around 8-15m of simulated time. The tgen output stops at that point, including heartbeats.

The problem occurs at shadow commit d64d07c65859090dc76a27fb3d9ef44ea9d756f3, but not on the previous commit b507cc1ed0fec74a0d02448401578f8b07add825.

After hacking up the minimal tor unit test a bit, I'm able to reproduce locally: https://github.com/sporksmith/shadow/tree/repro-bug. I extended the length of the simulation time, removed the non-tor clients since they're unrelated afaict. I added more tor clients, though I'm not sure that's essential. In this setup the bug takes a while longer to trigger - e.g. over an hour (see example below)

By attaching gdb to the fileserver tgen after it stops producing output, I was able to verify that it's hanging in a call to `epoll_wait`, with ~a timeout of 1 ms~ [edit: no timeout. One of the file descriptors watched by the epoll is a timerfd. See below.] I can confirm in the Shadow log that the process isn't scheduled again after that.

### PR DESCRIPTION
**Pull request by sporksmith**
Fixes #1623

### CODE REVIEW

**Comment by sporksmith** [comment]
This seems to fix the bug in my local repro. Trying it out on the larger tor congestion control sim here https://gitlab.torproject.org/jnewsome/sponsor-61-sims/-/jobs/35639

**Comment by sporksmith** [comment]
Just realized how https://github.com/shadow/shadow/pull/1583/commits/a18da0585c9f526877117adfc6ff8ceada556cca broke this in the first place. I'd removed `cond->signalPending = false;`, thinking it was effectively a no-op since we're no longer listening at that point. That's incorrect - we *are* still listening at that point, so flipping the boolean there does allow the signal to be scheduled again in the case that we decide not to actually run the process below.

Going to make a small simplifcation

**Comment by sporksmith** [comment]
It's probably worth adding a focused unit test that catches this, but I probably won't get to it until I'm back on Tuesday. Would be good to merge this sooner to unbreak shadow @ head. Opened #1628 to add the regression test.

File: src/main/host/syscall_condition.c [hunk 1]
```diff
@@ -310,6 +309,8 @@ static void _syscallcondition_signal(Host* host, void* obj, void* arg) {
     bool wasTimeout = (bool)arg;
     MAGIC_ASSERT(cond);
 
+    cond->signalPending = false;
```
Comment (robgjansen) [inline src/main/host/syscall_condition.c:312]: Might we worth a comment:
The signal task is now being executed by the worker and is no longer pending in the host's event queue. This is necessary, since it's possible that we want to schedule another signal task before this condition object is destroyed.

**Review by robgjansen — APPROVED** [review]

File: src/main/host/syscall_condition.c (hunk 1 above)
Comment (sporksmith) [reply src/main/host/syscall_condition.c:315]: Done
