### PR TITLE
Fix fstatat

### LINKED ISSUE #1332: 'process_getWriteablePtr()' assertion fails in 'syscallhandler_newfstatat()'
The `syscallhandler_newfstatat()` syscall handler seems to cause an assertion in `process_getWriteablePtr()` to fail in ptrace and hybrid modes.

```
**ERROR ENCOUNTERED**
	At process: 11036 (parent 11034)
	At file: /__w/shadow/shadow/src/main/host/process.c
	At line: 914
	At function: process_getWriteablePtr
	Message: proc->memoryReaders->len == 0
**BEGIN BACKTRACE**
Obtained 26 stack frames:
	/__w/shadow/shadow/build/src/main/shadow() [0x86adac]
	/__w/shadow/shadow/build/src/main/shadow(utility_handleError+0x34) [0x869bd4]
	/__w/shadow/shadow/build/src/main/shadow(process_getWriteablePtr+0xdd) [0x88219d]
	/__w/shadow/shadow/build/src/main/shadow(syscallhandler_newfstatat+0xd2) [0x89f512]
	/__w/shadow/shadow/build/src/main/shadow(syscallhandler_make_syscall+0x1b62) [0x898e12]
	/__w/shadow/shadow/build/src/main/shadow() [0x88b7ce]
	/__w/shadow/shadow/build/src/main/shadow() [0x888907]
	/__w/shadow/shadow/build/src/main/shadow(threadptrace_resume+0x198) [0x887e88]
	/__w/shadow/shadow/build/src/main/shadow(thread_resume+0xb1) [0x8848a1]
	/__w/shadow/shadow/build/src/main/shadow(process_continue+0x129) [0x8809f9]
	/__w/shadow/shadow/build/src/main/shadow() [0x883223]
	/__w/shadow/shadow/build/src/main/shadow() [0x881259]
	/__w/shadow/shadow/build/src/main/shadow(task_execute+0x6a) [0x87230a]
	/__w/shadow/shadow/build/src/main/shadow(event_execute+0x121) [0x871d21]
	/__w/shadow/shadow/build/src/main/shadow(worker_runEvent+0x32) [0x8737e2]
	/__w/shadow/shadow/build/src/main/shadow() [0x86cfee]
	/__w/shadow/shadow/build/src/main/shadow(_workerpool_startTaskFn+0x7c) [0x872acc]
	/__w/shadow/shadow/build/src/main/shadow(workerpool_startTaskFn+0xa3) [0x873313]
	/__w/shadow/shadow/build/src/main/shadow(scheduler_continueNextRound+0x5e) [0x86cf7e]
	/__w/shadow/shadow/build/src/main/shadow(manager_run+0x9f) [0x8548cf]
	/__w/shadow/shadow/build/src/main/shadow(controller_run+0x203) [0x852583]
	/__w/shadow/shadow/build/src/main/shadow() [0x851d76]
	/__w/shadow/shadow/build/src/main/shadow(main_runShadow+0x46b) [0x851a4b]
	/__w/shadow/shadow/build/src/main/shadow(main+0x22) [0x851582]
	/lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0xd5) [0x7f73b8f6b565]
	/__w/shadow/shadow/build/src/main/shadow(_start+0x2e) [0x85149e]
**END BACKTRACE**
**ABORTING**
```

```
43% tests passed, 107 tests failed out of 187

Total Test time (real) =  42.63 sec

The following tests FAILED:
	  5 - bindc-shadow-hybrid (Failed)
	  6 - bindc-shadow-ptrace (Failed)
	  9 - clone-shadow-hybrid (Failed)
	 10 - clone-shadow-ptrace (Failed)
	 12 - config-convert-run-shadow (Failed)
	 14 - config-stdin-shadow-hybrid (Failed)
         ...
```

We've only seen this occur on Ubuntu 21.04, likely because `syscallhandler_newfstatat()` wasn't being called on other platforms.

### PR DESCRIPTION
**Pull request by sporksmith**
* TypedPluginPtr: make slice method generic over RangeBounds
* MemoryManager.read_ptr: let caller slice instead of taking offset
* MemoryManager: generalize read_ptr -> readv_ptr
* Split MemoryReader.copy to read_some and read_exact
* MemoryReader: split as_ref into ref_some and ref_exact
* Reimplement process_getReadableString using new Reader API
* Add process_readString
* fileat syscalls: fix memory access bugs
* Add test for fstatat

Fixes #1332

### CODE REVIEW

File: src/main/host/memory_manager.rs [hunk 1]
```diff
@@ -344,8 +362,24 @@ where
...
+            }
+            let (prefix, suffix) = buf.split_at_mut(this_toread);
+            buf = suffix;
+            slices.push(prefix);
+            toread -= this_toread;
+        }
+        let rv = self
+            .memory_manager
+            .readv_ptrs(&mut slices, &[self.ptr.slice(offset..)]);
+        rv
```
Comment (stevenengler) [inline src/main/host/memory_manager.rs:389]: 1. This seems like it's mixing counts (`buf.len()`) with bytes (`page_size()`). Should this be using `buf.len() * sizeof(T)`?
2. This seems to be reading in chunks of `page_size()`, but the chunks don't seem to be aligned at page boundaries if `self.ptr` itself isn't aligned to a page boundary.

File: src/main/host/memory_manager.rs [hunk 2]
```diff
@@ -329,15 +343,9 @@ where
...
-            .readv_ptrs(&mut [buf], &[self.ptr.slice(offset..)])?;
-        if nread != buf.len() {
-            Err(Errno::EFAULT)
-        } else {
-            Ok(())
-        }
+    fn read_some(&self, offset: usize, buf: &mut [T]) -> Result<usize, Errno> {
+        self.memory_manager
+            .readv_ptrs(&mut [buf], &[self.ptr.slice(offset..)])
     }
```
Comment (stevenengler) [inline src/main/host/memory_manager.rs]: In order to stay consistent with the other functions, I think `read_some()` should return the number of `T` items, not the number of bytes returned by `readv_ptrs()`. So it should return `self.memory_manager.readv_ptrs() / size_of(T)`.

File: src/main/host/memory_manager.rs [hunk 3]
```diff
@@ -2000,6 +2011,20 @@ mod export {
...
 
+    #[no_mangle]
+    pub unsafe extern "C" fn memorymanager_readString<'a>(
+        reader: *const MemoryReader<'a, u8>,
+        str: *mut libc::c_char,
+        strlen: libc::size_t,
+    ) -> libc::ssize_t {
+        let reader = &*reader;
+        let dst = std::slice::from_raw_parts_mut(str as *mut u8, strlen);
```
Comment (stevenengler) [inline src/main/host/memory_manager.rs:2019]: I think it would be good to assert that `str` here isn't null.

**Review by stevenengler — CHANGES_REQUESTED** [review]

File: src/main/host/memory_manager.rs [hunk 4]
```diff
@@ -1658,24 +1670,49 @@ impl MemoryManager {
...
+                base: usize::from(src.ptr()),
+                len: src.cast::<u8>().unwrap().len(),
+            })
+            .collect();
+        let dsts: Vec<_> = dsts
+            .iter_mut()
+            .map(|dst: &mut &mut [T]| -> nix::sys::uio::IoVec<&mut [u8]> {
+                let slice =
+                    unsafe { std::slice::from_raw_parts_mut((*dst).as_mut_ptr(), dst.len()) };
+                nix::sys::uio::IoVec::from_mut_slice(pod::to_u8_slice_mut(slice))
```
[the remark this answers is not in the document]
Comment (stevenengler) [reply src/main/host/memory_manager.rs]: Nvm, I see this was changed in a later commit.

File: src/main/host/memory_manager.rs [hunk 5]
```diff
@@ -380,7 +387,12 @@ where
         // overwrite it.
         // SAFETY: any bit pattern is valid Pod.
         unsafe { vec.set_len(self.len()) };
-        self.memory_manager.read_ptr(&mut vec, self.ptr)?;
+        let nread = self
+            .memory_manager
+            .readv_ptrs(&mut [&mut vec], &[self.ptr])?;
+        if nread != vec.len() {
+            return Err(Errno::EFAULT);
```
[the remark this answers is not in the document]
Comment (sporksmith) [reply src/main/host/memory_manager.rs]: Done (now in memory_manager.read_exact)

File: src/main/host/memory_manager.rs [hunk 6]
```diff
@@ -1658,24 +1670,49 @@ impl MemoryManager {
...
+            })
+            .collect();
+
+        self.readv_iovecs::<T>(&dsts, &srcs)
+    }
+
+    // Low level helper for reading directly from `srcs` to `dsts`.
+    // Returns the number of bytes read. Panics if the
+    // MemoryManager's process isn't currently active.
+    fn readv_iovecs<T: Pod + Debug>(
```
[the remark this answers is not in the document]
Comment (sporksmith) [reply src/main/host/memory_manager.rs]: Done (I'm surprised Rust didn't complain)

File: src/main/host/memory_manager.rs (hunk 3 above)
Comment (sporksmith) [reply src/main/host/memory_manager.rs:2053]: I started to add `debug_assert`s, but I think we can depend on Rust to do it for us. e.g. https://doc.rust-lang.org/src/core/slice/raw.rs.html#130

File: src/main/host/syscall_types.rs [hunk 7]
```diff
@@ -216,16 +216,27 @@ impl<T> TypedPluginPtr<T> {
     }
 
     /// Return a slice of this pointer.
-    pub fn slice(&self, range: std::ops::Range<usize>) -> TypedPluginPtr<T> {
-        assert!(range.end <= self.count);
-        assert!(range.start <= self.count);
+    pub fn slice<R: std::ops::RangeBounds<usize>>(&self, range: R) -> TypedPluginPtr<T> {
+        use std::ops::Bound;
+        let excluded_end = match range.end_bound() {
+            Bound::Included(e) => e + 1,
```
[the remark this answers is not in the document]
Comment (sporksmith) [reply src/main/host/syscall_types.rs:222]: IIUC overflow will be caught in Debug builds; given that, I don't think it's worth wrapping every arithmetic operation in checks. https://github.com/rust-lang/rfcs/pull/560

File: src/main/host/syscall_types.rs [hunk 8]
```diff
@@ -216,16 +216,27 @@ impl<T> TypedPluginPtr<T> {
...
+            Bound::Excluded(e) => *e,
+            Bound::Unbounded => self.count,
```
[the remark this answers is not in the document]
Comment (sporksmith) [reply src/main/host/syscall_types.rs:224]: I don't think so - we're getting the *excluded* end-bound. e.g. `buf[..buf.len()]` is all of `buf`.

**Comment by sporksmith** [comment]
I realized that currently if the caller calls `CopyingMemoryReader::ref_exact`, and it fails, later calls to `CopyingMemoryReader::ref_some` will also fail. I *also* realized that we already have a similar issue with `CopyingMemoryWriter::as_mut` and `CopyingMemoryWriter::as_mut_uninit`; the first call "wins".

I think what I'd like to do is move the public methods returning references into `MemoryManager`, so that the exact type of reference is determined at the time of creation. Probably better to save that for another PR, though.

Thank you for your patience and diligence reviewing all these iterations!

**Comment by sporksmith** [comment]
> I realized that currently if the caller calls CopyingMemoryReader::ref_exact, and it fails, later calls to CopyingMemoryReader::ref_some will also fail

Oh no, that's right I did fix that. But the way I fixed it is that we always go through the more complex `read_some` path when copying the data. If we move the ref-returning methods into the MemoryManager though, `ref_exact` can go through the simpler path (which may be marginally faster).  `mut` vs `mut_uninit` is the bigger issue.

File: src/main/host/memory_manager.rs (hunk 3 above)
Comment (stevenengler) [reply src/main/host/memory_manager.rs:2053]: I don't think debug asserts in the standard library run, for example this code doesn't panic: https://play.rust-lang.org/?version=nightly&mode=debug&edition=2018&gist=9fbb2471cca367c2624d2a04767e37e8

Comment (sporksmith) [reply src/main/host/memory_manager.rs:2053]: Oh wow, that's surprising. I'll go ahead and add it then. I see I also missed a few other comments somehow; will make another pass

File: src/main/host/memory_manager.rs [hunk 9]
```diff
@@ -330,7 +330,14 @@ where
     }
 
     fn copy(&self, offset: usize, buf: &mut [T]) -> Result<(), Errno> {
-        self.memory_manager.read_ptr(buf, self.ptr.slice(offset..))
+        let nread = self
+            .memory_manager
+            .readv_ptrs(&mut [buf], &[self.ptr.slice(offset..)])?;
+        if nread != buf.len() {
+            Err(Errno::EFAULT)
```
[the remark this answers is not in the document]
Comment (sporksmith) [reply src/main/host/memory_manager.rs]: Done (in helpers)

File: src/main/host/memory_manager.rs [hunk 10]
```diff
@@ -57,11 +71,14 @@ where
...
-        (&*self.reader).as_ref()
+    /// Get a reference to the readable prefix of the region.
+    pub fn ref_some(&self) -> Result<&[T], Errno> {
+        (&*self.reader).ref_some()
+    }
+
+    /// Get a reference to the whole region, or return an error.
+    pub fn ref_exact(&self) -> Result<&[T], Errno> {
+        (&*self.reader).ref_exact()
     }
```
[the remark this answers is not in the document]
Comment (sporksmith) [reply src/main/host/memory_manager.rs]: Done

File: src/main/host/memory_manager.rs (hunk 2 above)
Comment (sporksmith) [reply src/main/host/memory_manager.rs]: Done

File: src/main/host/memory_manager.rs (hunk 3 above)
Comment (sporksmith) [reply src/main/host/memory_manager.rs:2066]: Done

**Comment by stevenengler** [comment]
> > I realized that currently if the caller calls CopyingMemoryReader::ref_exact, and it fails, later calls to CopyingMemoryReader::ref_some will also fail
> 
> Oh no, that's right I did fix that. But the way I fixed it is that we always go through the more complex `read_some` path when copying the data. If we move the ref-returning methods into the MemoryManager though, `ref_exact` can go through the simpler path (which may be marginally faster). `mut` vs `mut_uninit` is the bigger issue.

I don't think I follow these comments, but I'll wait to see what the next change looks like :)

**Review by stevenengler — APPROVED** [review]
