### PR TITLE
Change proc map inode from i32 to u64

### LINKED ISSUE #2144: inode 'xxx': number too large to fit in target type
**Describe the issue**
I got an error when I run `./run.sh` or run `tornettools simulate ...`
image
- the complete report:

```
** Starting Shadow v2.0.0-716-g72a5e82f 2022-05-10--15:35:00 with GLib v2.64.6
thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: "Parsing line: 555555554000-55555555a000 r--p 00000000 fd:00 3729159655                 /home/xsz/.local/bin/tgen\nParsing inode '3729159655': number too large to fit in target type"', main/host/memory_manager/memory_mapper.rs:177:62
stack backtrace:
   0: rust_begin_unwind
             at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/std/src/panicking.rs:584:5
   1: core::panicking::panic_fmt
             at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/core/src/panicking.rs:143:14
   2: core::result::unwrap_failed
             at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/core/src/result.rs:1749:5
   3: shadow_rs::host::memory_manager::memory_mapper::MemoryMapper::new
   4: shadow_rs::host::memory_manager::MemoryManager::init_mapper
   5: memorymanager_initMapperIfNeeded
   6: syscallhandler_shadow_init_memory_manager
             at /home/xsz/shadow/src/main/host/syscall/shadow.c:136:9
   7: syscallhandler_make_syscall
             at /home/xsz/shadow/src/main/host/syscall_handler.c:400:13
   8: threadpreload_resume
             at /home/xsz/shadow/src/main/host/thread_preload.c:309:40
   9: thread_resume
             at /home/xsz/shadow/src/main/host/thread.c:112:30
  10: process_continue
             at /home/xsz/shadow/src/main/host/process.c:665:5
  11: process_continue
             at /home/xsz/shadow/src/main/host/process.c:641:6
  12: _process_start
             at /home/xsz/shadow/src/main/host/process.c:599:5
  13: event_execute
             at /home/xsz/shadow/src/main/core/work/event.c:90:9
  14: worker_runEvent
             at /home/xsz/shadow/src/main/core/worker.c:464:5
  15: _scheduler_runEventsWorkerTaskFn
             at /home/xsz/shadow/src/main/core/scheduler/scheduler.c:85:9
  16: _worker_run
             at /home/xsz/shadow/src/main/core/worker.c:434:13
  17: start_thread
             at /build/glibc-sMfBJT/glibc-2.31/nptl/pthread_create.c:477:8
  18: clone
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
fatal runtime error: failed to initiate panic, error 5
./run.sh: line 4: 823525 Aborted                 (core dumped) shadow --template-directory shadow.data.template tor-minimal.yaml > shadow.log
```

- the result of `uname -a`
image

```
Linux niuweina-System-Product-Name 5.11.0-38-generic #42~20.04.1-Ubuntu SMP Tue Sep 28 20:41:07 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
```

**Shadow**
 - Version: post the output of `shadow --version`  

```
Shadow v2.0.0-716-g72a5e82f 2022-05-10--15:35:00 with GLib v2.64.6
```

 - Which plug-ins you are using:  
tornettools

### PR DESCRIPTION
**Pull request by stevenengler**
I think inodes on Linux should always be [positive](https://docs.rs/libc/latest/libc/type.ino_t.html), and some filesystems support [64-bit inodes](https://www.mjr19.org.uk/sw/inodes64.html).

Probably fixes #2144.

### CODE REVIEW

File: src/main/utility/proc_maps.rs [hunk 1]
```diff
@@ -82,7 +82,7 @@ pub struct Mapping {
     pub offset: usize,
     pub device_major: i32,
     pub device_minor: i32,
-    pub inode: i32,
+    pub inode: u64,
```
Comment (sporksmith) [inline src/main/utility/proc_maps.rs:85]: Maybe worth adding adding a unit test that requires 64 bits, and/or a comment that we know 32 bits isn't enough.

**Review by sporksmith — APPROVED** [review]

File: src/main/utility/proc_maps.rs (hunk 1 above)
Comment (stevenengler) [reply src/main/utility/proc_maps.rs:85]: Added a unit test with a large inode value.
